image: gradle

stages:
    - test-domain
    - test-api
    - build

test-domain-job:
    stage: test-domain
    script:
        - ./gradlew :domain:test

test-api-job:
    stage: test-api
    script:
        - ./gradlew :api:test

build-job:
    stage: build
    script:
        - gradle build